language: node_js
node_js:
  - node
script:
  - npm build
  - echo "Commit sha - $TRAVIS_COMMIT"
  - mkdir -p dist/@wcs/root-config/$TRAVIS_COMMIT
  - mv dist/*.* dist/@wcs/root-config/$TRAVIS_COMMIT/
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "wcs-single-spa-demo"
  region: "us-east-1"
  cache-control: "max-age=31536000"
  acl: "public_read"
  local_dir: dist
  skip_cleanup: true
  on:
    branch: master