service: root-config

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: src/server.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
